service: twitchoji-ebs

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: twitchoji-deployment
    serverSideEncryption: AES256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Query
      Resource:
        - ${self:custom.moodsTableArn}
        - Fn::Join:
            - '/'
            - - ${self:custom.moodsTableArn}
              - '*'
  environment:
    TABLE_NAME: ${self:custom.moodsTableName}
    JWT_SECRET: hidden/hidden+hidden+hidden/hidden=
    RANGE_SECONDS: 2
    TWITCH_CLIENT_ID: hidden
    TWITCH_API_ENDPOINT: https://api.twitch.tv/extensions
    TWITCH_OWNER_ID: hidden

plugins:
  - serverless-plugin-epsagon
  - serverless-dynamodb-local
  - serverless-offline

functions:
  api:
    handler: src/api/index.handler
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: moods
          method: post
          cors:
            origin: '*'
            allowCredentials: true
      - http:
          path: moods
          method: get
          cors:
            origin: '*'
            allowCredentials: true
  broadcast:
    handler: src/broadcast/index.handler
    memorySize: 128
    timeout: 5
    events:
      - stream:
        type: dynamodb
        arn:
          Fn::GetAtt: [ MoodsTable, StreamArn ]

package:
  exclude:
    - .dynamodb/**

custom:
  epsagon:
    token: hidden
    appName: ${self:service}
  moodsTableArn:
    Fn::GetAtt: [MoodsTable, Arn]
  moodsTableName:
    Ref: MoodsTable
  dynamodb:
    start:
      port: 8001
      inMemory: true
      migrate: true

resources:
  Resources:
    MoodsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-moods
        SSESpecification:
          SSEEnabled: true
        AttributeDefinitions:
          - AttributeName: streamId
            AttributeType: S
          - AttributeName: datetime
            AttributeType: S
        KeySchema:
          - AttributeName: streamId
            KeyType: HASH
          - AttributeName: datetime
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: KEYS_ONLY
        BillingMode: PAY_PER_REQUEST
